# Generated by Django 3.1.2 on 2021-02-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cin_employee', models.CharField(max_length=200)),
                ('nom_employee', models.CharField(max_length=200)),
                ('prenom_employee', models.CharField(max_length=200)),
                ('spécialité_employee', models.CharField(max_length=200)),
                ('salaire_employee', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='projet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_projet', models.CharField(max_length=200)),
                ('date_debut_projet', models.DateTimeField()),
                ('date_fin_projet', models.FloatField()),
                ('type_projet', models.CharField(max_length=200)),
                ('employe', models.ManyToManyField(to='societes.employee')),
            ],
        ),
    ]
