# Generated by Django 3.1.2 on 2021-02-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='budjet_projet',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projet',
            name='date_fin_projet',
            field=models.DateTimeField(),
        ),
    ]
