# Generated by Django 3.1.2 on 2021-02-19 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societes', '0002_auto_20210218_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='employe',
            field=models.ManyToManyField(to='societes.Employee'),
        ),
    ]
