# Generated by Django 3.1.2 on 2021-02-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societes', '0003_auto_20210219_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='employe',
            field=models.ManyToManyField(to='societes.Employee'),
        ),
    ]
